Support setext-style headers
luciopaiva/markdown-toc pull request #1
Opened 2020-06-08 02:02 UTC by dnchu

For example:

```markdown
Minetest Lua Modding API Reference
==================================

* More information at <http://www.minetest.net/>
* Developer Wiki: <http://dev.minetest.net/>
* (Unofficial) Minetest Modding Book by rubenwardy: <https://rubenwardy.com/minetest_modding_book/>

Introduction
------------

Content and functionality can be added to Minetest using Lua scripting
in run-time loaded mods.
```

2020-06-13 16:01 UTC, luciopaiva requested changes
Hi @dnchu,

Sorry for the delay to review it, I've been really busy here.

I left a comment below, please give it a check.

Thanks!

2020-06-13 16:01 UTC, luciopaiva commented on index.js
> +            if (level != NaN && title != null) {
`something != NaN` always evaluates to true (try in your browser console).
Since it's always evaluating to true, I'd ask you to please check your logic again to see if it even makes sense to replace with `isNaN()` or if you should completely get rid of it.

2020-06-14 02:04 UTC, dnchu commented
No worries! A lot of things are happening right now so I completely understand!

2020-06-14 17:33 UTC, luciopaiva commented
LGTM.

2020-06-14 17:33 UTC, merged

2020-06-14 17:35 UTC, luciopaiva commented
Thanks for your contribution, @dnchu!